import type { EditorThemeClasses } from "lexical";

const EditorTheme: EditorThemeClasses = {
    ltr: "ltr",
    rtl: "rtl",
    paragraph: "editor-paragraph mb-4 leading-relaxed",
    quote: "editor-quote border-l-4 border-gray-300 pl-4 italic",
    heading: {
        h1: "editor-heading-h1 font-display text-4xl font-bold mb-6 mt-8 text-neutral-800 dark:text-neutral-100",
        h2: "editor-heading-h2 font-display text-2xl font-semibold mb-4 mt-6 text-neutral-800 dark:text-neutral-100",
        h3: "editor-heading-h3 font-display text-xl font-semibold mb-3 mt-5 text-neutral-800 dark:text-neutral-100",
        h4: "editor-heading-h4 font-display text-lg font-semibold mb-2 mt-4",
        h5: "editor-heading-h5 font-display text-base font-semibold mb-2 mt-3",
        h6: "editor-heading-h6 font-display text-sm font-semibold mb-1 mt-2",
    },
    list: {
        nested: {
            listitem: "editor-nested-list-item",
        },
        ol: "editor-list-ol list-decimal ml-6 space-y-1",
        ul: "editor-list-ul list-disc ml-6 space-y-1",
        listitem: "editor-list-item",
    },
    image: "editor-image",
    link: "editor-link text-primary hover:underline cursor-pointer",
    text: {
        bold: "editor-text-bold font-bold",
        italic: "editor-text-italic italic",
        overflowed: "editor-text-overflowed",
        hashtag: "editor-text-hashtag",
        underline: "editor-text-underline underline",
        strikethrough: "editor-text-strikethrough line-through",
        underlineStrikethrough: "editor-text-underlineStrikethrough underline line-through",
        code: "editor-text-code font-mono bg-neutral-100 dark:bg-neutral-800 rounded px-1 py-0.5 text-sm",
    },
    code: "editor-code font-mono bg-neutral-100 dark:bg-neutral-800 rounded p-4 block my-4 overflow-x-auto text-sm",
    codeHighlight: {
        atrule: "editor-tokenAttr text-blue-600",
        attr: "editor-tokenAttr text-blue-600",
        boolean: "editor-tokenProperty text-purple-600",
        builtin: "editor-tokenSelector text-green-600",
        cdata: "editor-tokenComment text-gray-500",
        char: "editor-tokenSelector text-green-600",
        class: "editor-tokenFunction text-red-600",
        "class-name": "editor-tokenFunction text-red-600",
        comment: "editor-tokenComment text-gray-500",
        constant: "editor-tokenProperty text-purple-600",
        deleted: "editor-tokenProperty text-purple-600",
        doctype: "editor-tokenComment text-gray-500",
        entity: "editor-tokenOperator text-yellow-600",
        function: "editor-tokenFunction text-red-600",
        important: "editor-tokenVariable text-orange-600",
        inserted: "editor-tokenSelector text-green-600",
        keyword: "editor-tokenAttr text-blue-600",
        namespace: "editor-tokenVariable text-orange-600",
        number: "editor-tokenProperty text-purple-600",
        operator: "editor-tokenOperator text-yellow-600",
        prolog: "editor-tokenComment text-gray-500",
        property: "editor-tokenProperty text-purple-600",
        punctuation: "editor-tokenPunctuation text-gray-500",
        regex: "editor-tokenVariable text-orange-600",
        selector: "editor-tokenSelector text-green-600",
        string: "editor-tokenSelector text-green-600",
        symbol: "editor-tokenProperty text-purple-600",
        tag: "editor-tokenProperty text-purple-600",
        url: "editor-tokenOperator text-yellow-600",
        variable: "editor-tokenVariable text-orange-600",
    },
};

export default EditorTheme;
